### ISSUE TITLE
attempt to in stall plugin pytest(-cov) bails when using pipenv

### ISSUE THREAD

**Issue by mcallaghan-bsm** [markfink/metrics.pylint#1]
As per https://pipenv.readthedocs.io/en/latest/, we're using pipenv to manage our dependencies.

What works:
, I can install metrics via pipenv using the command line directly, or as per Pylint file.

 1. Command line:
```
pipenv install --dev metrics
Installing metrics…
Adding metrics to Pipfile's [dev-packages]…
✔ Installation Succeeded 
```
 2. Edit Pipefile directly (add `metrics`) and install
```
[dev-packages]
metrics = "*"
```
```
pipenv install --dev
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/10 — 00:00:11
```

What does not work:
, if we try to install the plugins related to pytest;

 1. Command line:
```
# pipenv install --dev metrics metrics.pytest metrics.pytest-cov
Installing metrics…
Adding metrics to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing metrics.pytest…
Adding metrics.pytest to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing metrics.pytest-cov…
Adding metrics.pytest-cov to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing dependencies from Pipfile…
An error occurred while installing metrics-pytest! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:00:02
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting metrics-pytest']
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement metrics-pytest (from versions: none)', 'ERROR: No matching distribution found for metrics-pytest']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
```

 2. Via Pipfile errors in a different way
```
[dev-packages]
metrics = "*"
metrics.pytest = "*"
metrics.pytest-cov = "*"
```
```
+ export PIPENV_SKIP_LOCK=true
+ /bin/sh
# pipenv install --dev
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/project.py", line 527, in _parse_pipfile
    return tomlkit.parse(contents)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/tomlkit/api.py", line 49, in parse
    return Parser(string).parse()
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/tomlkit/parser.py", line 146, in parse
    key, value = self._parse_table()
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/tomlkit/parser.py", line 963, in _parse_table
    self._handle_dotted_key(values, _key, item)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/tomlkit/parser.py", line 451, in _handle_dotted_key
    table.append(_name, value)
AttributeError: 'String' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/toml/decoder.py", line 727, in load_line
    currentlevel[pair[0]]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/toml/decoder.py", line 730, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 578, in ensure_project
    if project.required_python_version:
  File "/usr/local/lib/python3.7/site-packages/pipenv/project.py", line 243, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get(
  File "/usr/local/lib/python3.7/site-packages/pipenv/project.py", line 509, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "/usr/local/lib/python3.7/site-packages/pipenv/project.py", line 531, in _parse_pipfile
    return toml.loads(contents)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 19 column 1 char 236)
```

```
# pipenv --version
pipenv, version 2018.11.26

# python3 --version
Python 3.7.3
```

**Comment by mcallaghan-bsm** [comment]
(this MAY actually be an issue in pipenv, but figured I'd start here since it seems limited/specific to the plugin itself, possibly naming convention dot vs. dash -- noticing some oddities there)

**Comment by mcallaghan-bsm** [comment]
Whoops!  I completely got this wrong.  It's _metrics.pylint_, not _metrics.pytest_ :)

```
# pipenv install --dev metrics metrics.pylint metrics.pytest-cov
Installing metrics…
Adding metrics to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing metrics.pylint…
Adding metrics.pylint to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing metrics.pytest-cov…
Adding metrics.pytest-cov to Pipfile's [dev-packages]…
✔ Installation Succeeded 
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:00:02
```

```
[dev-packages]
metrics = "*"
metrics-pylint = "*"
metrics-pytest-cov = "*"
```

```
# pipenv install --dev
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:00:02
```
